

sonar.projectKey=jiancha
sonar.projectName=JianCha
sonar.projectVersion=1.0

sonar.sources=implementations
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_0ae813eac1ae5cbfa8f1295fc02b49ea04d3cae2