sonar.projectKey=Sirawit04_2025-ITCS383-JianCha
sonar.organization=Sirawit04

sonar.host.url=https://sonarcloud.io

sonar.sources=implementations/backend/src
sonar.tests=implementations/backend/tests

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=implementations/backend/coverage/lcov.info
