sonar.projectKey=Sirawit04_2025-ITCS383-JianCha
sonar.organization=sirawit04

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
